baseURL = 'https://quanghoa24.github.io/'
languageCode = 'vi-vn'
title = 'Blog Lập Trình Mạng | Đào Quang Hòa'
theme = 'PaperMod'

[params]
    # Kích hoạt chế độ hồ sơ cá nhân để trang chủ đẹp hơn
    [params.profileMode]
        enabled = true
        title = "Đào Quang Hòa"
        subtitle = "Sinh viên CNTT | Chuyên sâu Network Programming"
        imageUrl = "images/avatar.jpg"

    # Menu điều hướng (Blog và Hồ sơ)
    [[menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "about"
        name = "Hồ sơ cá nhân"
        url = "/about/"
        weight = 20