baseURL = 'https://quanghoa24.github.io/'
languageCode = 'vi-vn'
title = 'Blog Láº­p TrÃ¬nh Máº¡ng | ÄÃ o Quang HÃ²a'
theme = 'PaperMod'

[params]
    # KÃ­ch hoáº¡t Home-info Mode Ä‘á»ƒ hiá»‡n giá»›i thiá»‡u á»Ÿ trang chá»§
    [params.homeInfoParams]
        Title = "ChÃ o má»«ng Ä‘áº¿n vá»›i Blog cá»§a HÃ²a! ğŸ‘‹"
        Content = "NÆ¡i chia sáº» kiáº¿n thá»©c vá» Socket, Java Backend vÃ  JavaScript Real-time."

    # Menu Ä‘iá»u hÆ°á»›ng
    [[menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "about"
        name = "Há»“ sÆ¡ cÃ¡ nhÃ¢n"
        url = "/about/"
        weight = 20