baseURL = 'https://quanghoa24.github.io/'
languageCode = 'vi-vn'
title = 'Blog Láº­p TrÃ¬nh Máº¡ng | ÄÃ o Quang HÃ²a'
theme = 'PaperMod'

[params]
    # Báº­t cháº¿ Ä‘á»™ Home-Info Ä‘á»ƒ hiá»‡n lá»i chÃ o chuyÃªn nghiá»‡p
    [params.homeInfoParams]
        Title = "ChÃ o má»«ng Ä‘áº¿n vá»›i Blog cá»§a HÃ²a! ğŸ‘‹"
        Content = "NÆ¡i chia sáº» kiáº¿n thá»©c vá» Socket Programming, Java Backend vÃ  Há»‡ thá»‘ng Real-time."

    # Cáº¥u hÃ¬nh Menu Ä‘á»ƒ hiá»‡n "Blog" vÃ  "Há»“ sÆ¡"
    [[menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "about"
        name = "Há»“ sÆ¡ cÃ¡ nhÃ¢n"
        url = "/about/"
        weight = 20